---
- name: Add user demo
  hosts: all

  tasks:
    - name: Add test user to uid 4002
      ansible.builtin.user:
        name: testuser
        comment: Test User
        uid: 4002
        group: wheel
